### ISSUE TITLE
Is there a way to pass context for resolver decorated with `@define`?

### ISSUE THREAD

**Issue by playpauseandstop** [vmagamedov/hiku#22]
_Subj_

I tried both,

```py
@pass_context
@define(Unknown)
def date_listing(ctx, something):
    ...
```

and,

```py
@define(Unknown)
@pass_context
def date_listing(something, ctx):
   ...
```

but it didn't work.

----

Resolver declared as,

```py
Node('document', [
    'dateListing', 
    document_sg, 
    String, 
    date_listing(
         each(...)
    )
])
```

----

And if there is no way for passing context to those resolvers, I'd like to know why. Thanks

**Comment by vmagamedov** [comment]
Currently there is no way to use `pass_context` with function definitions for use in expression. The idea was to make all the data available in the low-level graph and project this data using expressions into high-level graph. So every IO/side-effects are performed by low-level graph, and expressions are just pure functions without side-effects – as explicit as possible.

And you actually can use context in the function definitions, but explicitly, and this can be done by exposing data from the context in the low-level graph (context is also a source of data):
```python
LOW_LEVEL = Graph([
    Root([
        Field('context', None, expose_context),
    ]),
])

HIGH_LEVEL = Graph([
    Node('foo', [
        Field('bar', None, foo_subgraph.c(
            some_func(S.context, S.this.bar)
                      ^^^^^^^^^
        )),
    ]),
])
```
And I'd suggest not to expose the whole context as one field, but expose only what needs to be exposed as distinct fields.

Is this makes sense for you?

**Comment by playpauseandstop** [comment]
> Is this makes sense for you?

Yes, completely. Closing as `wontfix`, thanks for info
