### ISSUE TITLE
ValueError on specifying low level graph source

### ISSUE THREAD

**Issue by playpauseandstop** [vmagamedov/hiku#8]
Got unexpected `ValueError` on attempt to specify low level graph source,

```
  File "/work/app/graph/data.py", line 30, in <module>
    token_access_time_src = sa.FieldsQuery(DB_ENGINE_KEY, token_access_time)
  File "/usr/local/lib/python3.6/dist-packages/hiku/sources/sqlalchemy.py", line 24, in __init__
    self.primary_key, = from_clause.primary_key
ValueError: not enough values to unpack (expected 1, got 0)
```

----

Models defined as,

```py
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import UUID


token = sa.Table(
    'tokens',
    metadata,

    sa.Column('id', UUID(), primary_key=True),
    ...
)

token_access_time = sa.Table(
    'token_access_times',
    metadata,

    sa.Column(
        'token',
        None,
        sa.ForeignKey('tokens.token', ondelete='CASCADE'),
        nullable=False,
        unique=True),
    ...
)
```

Graph source definition,

```py
from hiku.sources import aiopg as sa

token_access_time_src = sa.FieldsQuery(DB_ENGINE_KEY, token_access_time)
token_src = sa.FieldsQuery(DB_ENGINE_KEY, token)
```

Low level graph nodes declared as,

```py
from hiku.graph import Node
from hiku.sources import aiopg as sa

...

    Node('token', [
        sa.Field('token', token_src),
        ...
    ]),

    Node('token_access_time', [
        sa.Field('token', token_access_time_src),
        ...
    ]),
```

----

- Python version: `3.6.1`
- Hiku version: `0.3.6.post1`
- SQLAlchemy version: `1.1.9`
- aiopg version: `0.13.0`

**Comment by vmagamedov** [comment]
Sorry for late response. Seems like `token_access_times` table doesn't have a primary key. Is this true? As I see, `token_access_times.token` column looks like primary key, but was not declared this way. It is still possible to use this table without changes (if it was defined this way intentionally) by explicitly specifying `primary_key` optional argument in `FieldsQuery.__init__` method:
```python
token_access_time_src = sa.FieldsQuery(DB_ENGINE_KEY, token_access_time,
                                       primary_key=token_access_time.c.token)
```

**Comment by playpauseandstop** [comment]
@vmagamedov 

Can confirm. All works as expected after specifying `primary_key=...`. My bad for not looking deeply in docs/code. Thanks for pointing out.

Closing as `invalid`.
